import { Background } from "@components/background";
import Head from "next/head";
import styled from '@emotion/styled'

const Dev = styled.div`
  color: var(--test);
`

const Home = ({ projects }: { projects: any }) => {
  console.log(projects)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dev>hello world</Dev>
      <Background />
    </>
  );
};

export const getServerSideProps = async () => {
  const data = await fetch(
    `https://api.github.com/users/cookieMonsterDev/repos`
  ).then((response) => response.json());

  return {
    props: {
      projects: data,
    },
  };
};

export default Home;
