import { ToasterProvider } from "@/providers/toast-provider";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ToasterProvider />
      <body className="relative">{children}</body>
    </html>
  );
}
