import "./globals.css";
import type { Metadata } from "next";
import { AuthProvider } from "@/providers/auth-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className="relative">{children}</body>
      </html>
    </AuthProvider>
  );
}
